### ISSUE TITLE
Triggered sweep for OSC

### ISSUE THREAD

**Issue by banksean** [spectrome/patchcab#12]
**Is this feature  request for a module or Patchcab in general?**
- [ x ] Module

**Describe the solution you'd like**
Oscilloscopes IRL usually have a "triggered sweep" feature:
https://en.wikipedia.org/wiki/Oscilloscope#Triggered_sweep

It would be nice for the included OSC module to offer this as well.

It's very helpful for understanding the shape of a periodic wave.

I would be happy to write up PR for this if you don't already have plans to implement it.

This is a super cool project by the way! I had started to build something similar (using Web Components instead of Svelte, but whatever...) and this saves me a *ton* of work!

**Comment by rihardsgravis** [comment]
This has been now merged and released in version `1.1.1` 🎉
