### ISSUE TITLE
Fonts not rendering properly during screenshot

### ISSUE THREAD

**Issue by banksean** [spectrome/patchcab#14]
When I run `yarn build` in my local checkout, the screenshots it produces in `modules/` directories all use the default (seriffed, in my case) fonts rather than the expected Routed Gothic.

I thought perhaps it was just my own modules but this happens even when I run `yarn build` in the main `@patchcab/modules` package too, e.g:

![clock](https://user-images.githubusercontent.com/38789/116286452-17922300-a744-11eb-86ec-dd446ee6e5b2.png)

I added some logging to capture the js dev console output in `screenshot.ts` and it says this, which may be relevant:
```
PAGE LOG: %c * Tone.js v14.7.77 *  background: #000; color: #fff
PAGE LOG: The resource http://localhost:3000/assets/routed-gothic.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
PAGE LOG: The resource http://localhost:3000/assets/routed-gothic-wide.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

If I pause and inspect the elements in devtools, it looks like they have the proper font-face property (and the files apparently loaded successfully, per the logs above), it just isn't rendering the right font.

I hesitate to really call this a "bug" since vercel seems to generate these screenshots without this issue when it runs `build`, so I suspect the problem is somewhere on my end, but do you have ideas for things I should double-check?

So far, I've tried:
- in `screenshot.ts`: adding `--font-render-hinting=none` to `puppeteer.lauch` args
- in `index.html`: 
  - adding `type="font/woff2"` to the `<link rel="preload"...` links for the fonts
  - changing `font-display` to `block' in the `@font-face` CSS rules

Kind of grasping at straws here. Any other ideas? 

**Environment:**
 - OS: macOS 10.15.6
 - Browser (the one launched by puppeteer): Chromium Version 88.0.4298.0 (Developer Build) (x86_64)

**Comment by banksean** [comment]
And to clarify further: this is only a problem during screenshot.  The font renders properly when I run `yarn start` and use the application with Chrome browser interactively.

**Comment by rihardsgravis** [comment]
First of all - I am really sorry on the 7 month late response :/  Patchcab was set aside unfairly for some personal reasons.

There where actually two errors  that would cause the fonts not loading correctly -  the css import url was not pointing to incorrect location and the Puppeteer page did not wait for all assets loaded before creating the screenshot. The issues are now fixed and will be released on next release.
