### ISSUE TITLE
Module overlap bug

### ISSUE THREAD

**Issue by zarp-dev** [spectrome/patchcab#4]
Hi Richards!
I found a small bug in Patchcab.
I added a new module and it appeared on top of the existing one. Now I cannot move them, they are stuck.
The only way to move them is to delete one of them.

![Screenshot 2021-01-21 at 23 47 57](https://user-images.githubusercontent.com/65812041/105410761-7c207c00-5c43-11eb-9acd-83b8419cc539.png)

Thank you for making such a wonderful open source modular web synthesizer!

**Comment by rihardsgravis** [comment]
Hey @zarp-dev, thank you for the very first bug report 🙌

I found the issue and will push the fix shortly.
